#!/usr/bin/env zsh

eval "$_z4d_opt"

if [[ -n $_Z4D_TMUX ]]; then
  local pane
  pane="$(TMUX=$_Z4D_TMUX TMUX_PANE=$_Z4D_TMUX_PANE $_Z4D_TMUX_CMD capture-pane -p -e && print -n x)" || return
  typeset -g _z4d_saved_screen=$'\e[0m\e[H'${${pane//$'\n'/$'\e[49m\e[K\r\n'}%$'\r\nx'}
elif [[ -n $Z4D_SSH && -n $_Z4D_SSH_MARKER && -v _z4d_tty_fd ]]; then
  printf '\001z4d.%s%s' "$_Z4D_SSH_MARKER" 'save-screen     ' >&$_z4d_tty_fd
else
  return 1
fi
