#!/usr/bin/env zsh

local -i ret

if [[ -v widgets[-z4d-orig-zle-line-finish] ]]; then
  zle -- -z4d-orig-zle-line-finish "$@" || ret=$?
fi

if [[ -v _z4d_redraw_fd ]]; then
  zle -F "$_z4d_redraw_fd"
  exec {_z4d_redraw_fd}>&-
  unset _z4d_redraw_fd
fi

if [[ $BUFFER == *' ' ]] &&
   ! zstyle -t :z4d:history preserve-trailing-whitespace &&
   -z4d-is-valid-list "$PREBUFFER$BUFFER"; then
  BUFFER=${BUFFER%% #}
fi

unset POSTDISPLAY _z4d_autosuggest_buffer _z4d_autosuggestion
if [[ -v region_highlight ]]; then
  _zsh_highlight
fi

return ret
