#!/usr/bin/env zsh

(( ${+_z4d_dir_hist_fd} )) && -z4d-update-dir-history

() {
  eval "$_z4d_opt"
  while (( $#dirstack )) && ! pushd -q $1 &>/dev/null; do
    popd -q $1
  done
  (( $#dirstack ))
} "$@" && -z4d-redraw-prompt
