#!/usr/bin/env zsh

local file
zparseopts -D -F -- || return '_z4d_err()'
emulate zsh -o extended_glob -c 'local files=(${^@}(N))'
builtin set --
for file in "${files[@]}"; do
  -z4d-compile "$file"
done
