#!/usr/bin/env zsh

[[ -v _z4d_tty_fd ]] || return

builtin echoti civis >&$_z4d_tty_fd
builtin print -rnu $_z4d_tty_fd -- $'\e[H\e[2J'"${(pl:$((LINES-1))::\n:)}"
builtin zle -I
builtin zle -R
builtin print -rnu $_z4d_tty_fd -- $'\e[3J'
-z4d-cursor-show
